### ISSUE TITLE
Create-React-App

### ISSUE THREAD

**Issue by BenJensen2** [Team-Programming/Platform#1]
Need someone to create a React App to start the client side of the project.  If you need help understanding what that means, take a look here: https://reactjs.org/docs/create-a-new-react-app.html

Terminal Command: npx create-react-app

**Comment by SushanthReddy-49** [comment]
Hi Ben, is it just creating a New React App so that we can add all the HTML and CSS files in there ?

**Comment by BenJensen2** [comment]
Yup! Real simple
